### PR TITLE
test/logging: add log.toml file test

### PR DESCRIPTION
**Pull request by ustulation**
Add a test for log.toml logging. The log.toml file is detailed with comments on usage unlike the previous log.toml which existed in examples and was wrong in its content (i.e. there were invalid formats which could not produce a working sample).

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_utilities/58)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[test/log.toml, line 3 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/58#-KGLqfZ2-Mq9IHPYZD4T:-KGLqfZ2-Mq9IHPYZD4U:-1517041864) ([raw file](https://github.com/maidsafe/maidsafe_utilities/blob/fdfd6bc22c771cb3339161680dd8006994356ab2/test/log.toml#L3)):_
Nit-pick: I'd put a space after the "#", make "URL" uppercase, capitalize the first word and add full stops to user-facing documentation, even if it's just an inline comment like this. (Also below.)
(But I'm happy to do this in another commit.)

---

_[test/src/main.rs, line 1 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/58#-KGLrNQjNWUPB5Qcr0Zq:-KGLrNQk5bU4x6Q57QV0:-724931425) ([raw file](https://github.com/maidsafe/maidsafe_utilities/blob/fdfd6bc22c771cb3339161680dd8006994356ab2/test/src/main.rs#L1)):_
Should this be 2016? (But I'm also fine with 2015 since most of the code has just been moved here, right?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/58)_

**Comment by afck** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/58)_

**Comment by afck** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/58)_

**Pull request merged**
