### PR TITLE
feat/seeded RNG: change to use a single static seed

### PR DESCRIPTION
**Pull request by Fraser999**
This modifies the behaviour of  constructors to use a static value for the seed
throughout the lifetime of the process.

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_utilities/69)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Fraser999** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/lib.rs, line 31 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/69#-KKxSyQU2lys43d52hrz:-KKxSyQU2lys43d52hs-:-977902284) ([raw file](https://github.com/maidsafe/maidsafe_utilities/blob/563eb4965bd27b8a9d48eab436d296649f2241e1/src/lib.rs#L31)):_

> ``` Rust
> #![forbid(exceeding_bitshifts, mutable_transmutes, no_mangle_const_items, unknown_crate_types,
>           warnings)]
> #deny(bad_style, deprecated, drop_with_repr_extern, improper_ctypes, missing_docs,
> ```

I had to move `bad_style` from forbid to deny since lazy_static's macro disables this lint for some types it creates.

---

_Comments from [Reviewable_

**Comment by afck** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/69)_

**Pull request merged**
