### PR TITLE
Make thread! into a function and rename it named

### PR DESCRIPTION
**Pull request by canndrew**
This provides alternative to the now deprecated `thread!` macro into a function so that the `line!` and `column!` macro will work correctly inside of it.

---

This change is [Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_utilities/65)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/thread.rs, line 91 [r2]](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/65#-KL0okbb9as7ufww0SQV:-KL0okbb9as7ufww0SQW:-650492068) ([raw file](https://github.com/maidsafe/maidsafe_utilities/blob/0fc1ed2c88785ba4714531b6ec0744fbe79e7354/src/thread.rs#L91)):_

> ``` Rust
> {
>     let thread_name: String = thread_name.into();
>     let t = std::thread::Builder::new().name(thread_name)
> ```

call it `joiner` or `jh` or something. Single alphabet might be too much reduction in length ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/65)_

**Comment by madadam** [comment]
I  propose that the `named` function returns `RaiiThreadJoiner` instead of `JoinHandle`. To allow spawning detached threads too, I propose augmenting `RaiiThreadJoiner` with a `release` method which consumes `self` and returns the `JoinHandle`. That way, the more common case (scoped threads) would be more convenient to use while making the less common case (detached threads) still possible.

**Comment by ustulation** [comment]
Yes the `release`/`detach` would be useful. Then we can have it return `RaiiThreadJoiner` by default.

**Comment by ustulation** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/maidsafe_utilities/65)_

**Pull request merged**
